### PR TITLE
Added prettier

### PR DESCRIPTION
**Pull request by jvvan**
Added prettier to dependencies and `npm run prettier`.

### CODE REVIEW

**Comment by Gr8z** [comment]
@j122j Looks good, but is everything in ``prettier.json`` different from the default?

**Comment by jvvan** [comment]
arrowParens is different, but I still wanted to make a config file so other developers can change it easily.

**Comment by Gr8z** [comment]
Alright fair enough, though I think the trailing commas should be turned off by default.

**Comment by jvvan** [comment]
By default it is enabled, but you can change it if you want.

**Comment by Gr8z** [comment]
Could you turn it off and run prettier again on the repo?

**Comment by jvvan** [comment]
Done.

**Pull request merged**
